//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoKrt.Exception.MessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancoKrt.Exception.MessageResource.ErrorMessageResource", typeof(ErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number is required.
        /// </summary>
        public static string ACCOUNT_NUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency not found.
        /// </summary>
        public static string AGENCY_NOT_FOUND {
            get {
                return ResourceManager.GetString("AGENCY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency number is required.
        /// </summary>
        public static string AGENCY_NUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("AGENCY_NUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        public static string AMOUNT_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance must be provided and greater than zero.
        /// </summary>
        public static string BALANCE_REQUIRED {
            get {
                return ResourceManager.GetString("BALANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is required.
        /// </summary>
        public static string DOCUMENT_REQUIRED {
            get {
                return ResourceManager.GetString("DOCUMENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string ID_REQUIRED {
            get {
                return ResourceManager.GetString("ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It´s not possible to proceed due to insufficient founds.
        /// </summary>
        public static string INSUFFICIENT_FOUNDS {
            get {
                return ResourceManager.GetString("INSUFFICIENT_FOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found.
        /// </summary>
        public static string KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found, no register matches the identifier mentioned.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to transfer amount higher than your limit transaction.
        /// </summary>
        public static string TRANSACTION_AMOUNT_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("TRANSACTION_AMOUNT_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction limit is required.
        /// </summary>
        public static string TRANSACTION_LIMIT_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSACTION_LIMIT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
